version: '3'
services:
  auth_service:
    build: ./AuthService/app
    ports:
      - "50001:50001"
    environment:
      - AUTH_PORT=50001
      - AUTH_HOST=auth_service
      - DB_HOST=db
      - PYTHONPATH=AuthService/app
    networks:
      - grpc_network

  article_service:
    build: ./ArticleService/app
    ports:
      - "50002:50002"
    environment:
      - ARTICLE_PORT=50002
      - AUTH_HOST=auth_service
      - AUTH_PORT=50001
      - DB_HOST=db
      - PYTHONPATH=ArticleService/app
    networks:
      - grpc_network
    depends_on:
      - auth_service
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=rpcarticle-db-1
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456 # MySQL에서는 루트 비밀번호 설정이 필요
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - grpc_network
    command: --default-authentication-plugin=mysql_native_password # 이 옵션은 필요에 따라 추가

networks:
  grpc_network:
    driver: bridge

volumes:
  db-data:
